version: '3.8'

services:
  app:
    image: php:8.4-fpm
    container_name: laravel_app
    restart: always
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - laravel
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:8.3
    container_name: laravel_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel

  redis:
    image: redis:7.2
    container_name: laravel_redis
    restart: always
    volumes:
      - redis_data:/data
    networks:
      - laravel

  caddy:
    image: caddy:latest
    container_name: laravel_caddy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
      - ./:/var/www/html
    networks:
      - laravel
    depends_on:
      - app

volumes:
  db_data:
  redis_data:
  caddy_data:
  caddy_config:

networks:
  laravel:
    driver: bridge
